= 3scale Early Adapter Deployment

:numbered:


== Overview
Red Hat is offering an Early Adapter program to select partners and customers for the 2.12 release of the 3scale API Manager.

Of critical importance in this release is the ability to run the link:https://issues.redhat.com/browse/THREESCALE-5725[API Manager in a FIPS enabled] OpenShift cluster.


The container images for the beta release of the API Manager are managed in a private `quay.io` organization.
This document will guide you through the procedure to access these beta release images and provision the API Manager.

== Pre-requisites


. OpenShift Minimum Requirements:
.. Version:  4.10
.. RAM:  48 GB
.. CPU:  16 cores
.. Filesystem:
... 5 PVCs of 5 GBs each of RWO
... 1 PVC of 5 GBs of RWX
.. FIPS enabled
.. Suggested:  wildcard certificate from known Certificate Authority for application routes exposed through OpenShift

. TO-DO: Demonstrate how to validate that FIPS is enabled


. Contact 3scale engineering team or your Red Hat SA for the credentials to the private quay.io image repository.

. Based on the credentials provided, set the following environment variables in your shell:
+
-----
export PRIVATE_QUAY_ACCOUNT_NAME="CHANGE_ME"
export PRIVATE_QUAY_ACCOUNT_PASSWORD="CHANGE_ME"
-----



== Procedure

=== OpenShift Pull Secret
. Download your existing OpenShift pull-secret to a temp file called _private-quay-enabled-pull-secret.json_:
+
-----
$ oc get secret/pull-secret \
            -n openshift-config \
            --template='{{index .data ".dockerconfigjson" | base64decode}}' \
            > /tmp/private-quay-enabled-pull-secret.json
-----

. Add credentials of private quay image repository account to pull secret:
+
-----
$ oc registry login --registry="quay.io:443/3scale" \
        --auth-basic="$PRIVATE_QUAY_ACCOUNT_NAME:$PRIVATE_QUAY_ACCOUNT_PASSWORD" \
        --to=/tmp/private-quay-enabled-pull-secret.json
-----

. Update pull secret for your OpenShift cluster:
+
-----
$ oc set data secret/pull-secret \
        -n openshift-config \
        --from-file=.dockerconfigjson=/tmp/private-quay-enabled-pull-secret.json
-----


. Verify your cluster pull-secret now contains two references to quay image repositories (similar to the following) :
+
-----
$ oc get secret/pull-secret \
    -n openshift-config \
    --template='{{index .data ".dockerconfigjson" | base64decode}}' \
    | jq -r '.auths|to_entries | .[]|select(.key | contains("quay.io"))'


{
  "key": "quay.io",
  "value": {
    "auth": "xxxxxxxxxxxxxxxxxxxx",
    "email": "rhpds-admins@redhat.com"
  }
}
{
  "key": "quay.io:443/3scale",
  "value": {
    "auth": "xxxxxxxxxxxxxxxxxx"
  }
}
-----


=== Custom ImageContentSourcePolicy

. Apply custom _ImageContentSourcePolicy_ :
+
-----
$ oc apply -f https://raw.githubusercontent.com/jbride/3scale-deployment/2.12-beta/operators/3scale/quay-registry-icsp.yaml
-----


=== 3scale API Manager operator resources

==== Operator Lifecycle Manager (OLM) catalog

Start by creating a new namespace and deploying a custom CatalogSource (defining channels to alpha & beta 3scale images) in this namespace. 

. Create _rhi-apimgmt_ project
+
-----
$ oc new-project rhi-apimgmt
-----

. Create CatalogSource for 3scale beta operator:
+
-----
$ oc create -n rhi-apimgmt \
        -f https://raw.githubusercontent.com/jbride/3scale-deployment/2.12-beta/operators/3scale/3scale-operator-beta_catalogsource.yaml 
-----

. Observe creation of new pod corresponding to CatalogSource:
+
-----
$ oc get pod -n rhi-apimgmt

NAME                                                    READY   STATUS    RESTARTS   AGE
threescale-productized-operators-latest-catalog-74l88   1/1     Running   0          17s
-----


==== 3scale Operator
. Create _operator-group_ :
+
-----
$ oc create -n rhi-apimgmt \
        -f https://raw.githubusercontent.com/jbride/3scale-deployment/2.12-beta/operators/3scale/3scale-operator-operatorgroup.yaml
-----

. Create operator subscription :
+
-----
$ oc create -n rhi-apimgmt \
        -f https://raw.githubusercontent.com/jbride/3scale-deployment/2.12-beta/operators/3scale/3scale-operator-subscription.yaml
-----

.. Verify Operator Lifecycle Manager job that installs 3scale operator:
+
-----
$ oc describe job $( oc get jobs | sed -n 2p | awk '{print $1}' )
-----
+
Results should be similar to the following:
+
-----
Name:                     8a7e08b2d268639550cdd6557a92916b8be29a89bda1a28d14e3519e465f161
Namespace:                rhi-apimgmt
Selector:                 controller-uid=69b8ff51-a3ad-4254-856b-7d0a129a321c
Labels:                   controller-uid=69b8ff51-a3ad-4254-856b-7d0a129a321c
                          job-name=8a7e08b2d268639550cdd6557a92916b8be29a89bda1a28d14e3519e465f161
Annotations:              batch.kubernetes.io/job-tracking: 
Parallelism:              1
Completions:              1
Completion Mode:          NonIndexed
Start Time:               Mon, 04 Apr 2022 11:04:33 -0600
Completed At:             Mon, 04 Apr 2022 11:04:46 -0600
Duration:                 13s
Active Deadline Seconds:  600s
Pods Statuses:            0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=69b8ff51-a3ad-4254-856b-7d0a129a321c
           job-name=8a7e08b2d268639550cdd6557a92916b8be29a89bda1a28d14e3519e465f161
  Init Containers:
   util:
    Image:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:137866ad70b94281a575ae818fafb4a2ad1cd057555e87688139b0456f932786
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/cp
      -Rv
      /bin/cpb
      /util/cpb
    Requests:
      cpu:        10m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /util from util (rw)
   pull:
    Image:      quay.io/3scale/rh-3scale-operator-bundle:3scale-amp-2.12-rhel-7-containers-alpha-48872-20220404110605
    Port:       <none>
    Host Port:  <none>
    Command:
      /util/cpb
      /bundle
    Requests:
      cpu:        10m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /bundle from bundle (rw)
      /util from util (rw)
  Containers:
   extract:
    Image:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:33d8c78741aada4801ee7c03d93b44e03753323b48002eda12b05d07f00c99e6
    Port:       <none>
    Host Port:  <none>
    Command:
      opm
      alpha
      bundle
      extract
      -m
      /bundle/
      -n
      rhi-apimgmt
      -c
      8a7e08b2d268639550cdd6557a92916b8be29a89bda1a28d14e3519e465f161
      -z
    Requests:
      cpu:     10m
      memory:  50Mi
    Environment:
      CONTAINER_IMAGE:  quay.io/3scale/rh-3scale-operator-bundle:3scale-amp-2.12-rhel-7-containers-alpha-48872-20220404110605
    Mounts:
      /bundle from bundle (rw)
  Volumes:
   bundle:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   util:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  26m   job-controller  Created pod: 8a7e08b2d268639550cdd6557a92916b8be29a89bda1a28d14e3519e46fltgp
  Normal  Completed         26m   job-controller  Job completed
-----

. View version of operator image from auto-generated _InstallPlan_ :
+
-----
$ oc get installplan -n rhi-apimgmt -o json      | jq -r .items[].status.bundleLookups[].path


quay.io/3scale/rh-3scale-operator-bundle:3scale-amp-2.12-rhel-7-containers-alpha-52412-20220420173941
-----



. Error in events log:
+
-----
$ 3m55s       Normal    BackOff               pod/threescale-operator-controller-manager-v2-967ccc86b-h787b         Back-off pulling image "registry.redhat.io/3scale-amp2/3scale-rhel7-operator@sha256:11136be82ac26cdc1b2b9d7623936b5e518765cf118fe51b427f05a98b1c75b9"
-----

== Reference

link:https://docs.google.com/document/d/1Kwic_97NCxZmzi122Dnc57m18YwkWhc1CE1Qr67rVjs/edit#heading=h.xrmfiql8o3uh[3scale Early Access Image Delivery]
